#!/usr/bin/python3

import subprocess
import time
import argparse

# parse arguments
parser = argparse.ArgumentParser()
parser.add_argument("interpreter", help="the interpreter the file should be executed with", type=str)
parser.add_argument("file", help="file to be executed", type=str)
args = parser.parse_args()

# get args from argparse
interpreter = args.interpreter
file = args.file

# check if interpreter is valid
try:
    subprocess.call(["which", interpreter])
except:
    print(interpreter, "not installed, not in $PATH or typo?")

# This while runs until you press ctr-c
# This must be changed to a more elegant soution!!!
while True:
    # read file
    text = open(file).read()

    # check if file content has changed
    # and sleep for 1 sec
    while text == open(file).read():
        time.sleep(1)

    # get screen width
    dims = subprocess.check_output(['stty size', 'r'], shell=True).split()
    width = int(dims[1].decode('utf-8'))

    # make title string
    title = "#" * int((width / 2 - 12)) + " Executing New Version  " + "#" * int((width / 2 - 12))

    # print title
    print(title)

    # prepare command for execution
    command = interpreter, file

    # get time before command execution
    start_time = time.time()

    # execute command
    subprocess.call(command)

    # make result-title string
    title = "#" * int((width / 2 - 9)) + " Performance Data " + "#" * int((width / 2 - 9))

    # print result-title
    print(title)

    # print time the command has taken
    exec_time = str(time.time() - start_time) + " sec"
    print("#", exec_time, " " * (width - len(exec_time) - 5), "#")

    # print end seperator and newline
    print("#" * width + "\n")
